apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-label-bodger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-label-bodger
subjects:
- kind: ServiceAccount
  name: node-label-bodger
  namespace: kube-system
