apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-label-bodger
  name: node-label-bodger
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: node-label-bodger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-label-bodger
    spec:
      containers:
      - image: cryptofacilities/node-label-bodger:0.6
        imagePullPolicy: IfNotPresent
        name: node-label-bodger
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-label-bodger
      serviceAccountName: node-label-bodger
      terminationGracePeriodSeconds: 30
